export const AUTH_GET_OWN_USERDATA_REQUEST = "AUTH_GET_OWN_USERDATA_REQUEST";
export const AUTH_GET_OWN_USERDATA_SUCCESS = "AUTH_GET_OWN_USERDATA_SUCCESS";
export const AUTH_GET_OWN_USERDATA_FAILURE = "AUTH_GET_OWN_USERDATA_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_FAILURE = "AUTH_SIGNUP_FAILURE";

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const AUTH_LOGOUT_REQUEST = "AUTH_LOGOUT_REQUEST";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_LOGOUT_FAILURE = "AUTH_LOGOUT_FAILURE";

export const ADVERTS_LOADED_REQUEST = "ADVERTS_LOADED_REQUEST";
export const ADVERTS_LOADED_SUCCESS = "ADVERTS_LOADED_SUCCESS";
export const ADVERTS_LOADED_FAILURE = "ADVERTS_LOADED_FAILURE";

export const ADVERTS_ORDER_REQUEST = "ADVERTS_ORDER_REQUEST";
export const ADVERTS_ORDER_SUCCESS = "ADVERTS_ORDER_SUCCESS";
export const ADVERTS_ORDER_FAILURE = "ADVERTS_ORDER_FAILURE";

export const ADVERTS_CREATED_REQUEST = "ADVERTS_CREATED_REQUEST";
export const ADVERTS_CREATED_SUCCESS = "ADVERTS_CREATED_SUCCESS";
export const ADVERTS_CREATED_FAILURE = "ADVERTS_CREATED_FAILURE";

export const ADVERTS_UPDATED_REQUEST = "ADVERTS_UPDATED_REQUEST";
export const ADVERTS_UPDATED_SUCCESS = "ADVERTS_UPDATED_SUCCESS";
export const ADVERTS_UPDATED_FAILURE = "ADVERTS_UPDATED_FAILURE";

export const ADVERTS_DETAIL_REQUEST = "ADVERTS_DETAIL_REQUEST";
export const ADVERTS_DETAIL_SUCCESS = "ADVERTS_DETAIL_SUCCESS";
export const ADVERTS_DETAIL_FAILURE = "ADVERTS_DETAIL_FAILURE";

export const ADVERTS_DELETE_REQUEST = "ADVERTS_DELETE_REQUEST";
export const ADVERTS_DELETE_SUCCESS = "ADVERTS_DELETE_SUCCESS";
export const ADVERTS_DELETE_FAILURE = "ADVERTS_DELETE_FAILURE";

export const ADVERTS_TAGS_REQUEST = "ADVERTS_TAGS_REQUEST";
export const ADVERTS_TAGS_SUCCESS = "ADVERTS_TAGS_SUCCESS";
export const ADVERTS_TAGS_FAILURE = "ADVERTS_TAGS_FAILURE";

export const CHANGE_PAGE_REQUEST = "CHANGE_PAGE_REQUEST";
export const CHANGE_PAGE_SUCCESS = "CHANGE_PAGE_SUCCESS";
export const CHANGE_PAGE_FAILURE = "CHANGE_PAGE_FAILURE";

export const CHANGE_LANGUAGE_REQUEST = "CHANGE_LANGUAGE_REQUEST";
export const CHANGE_LANGUAGE_SUCCESS = "CHANGE_LANGUAGE_SUCCESS";
export const CHANGE_LANGUAGE_FAILURE = "CHANGE_LANGUAGE_FAILURE";

export const UI_RESET_ERROR = "UI_RESET_ERROR";

export const SIGN_EMAIL_REQUEST = "SIGN_EMAIL_REQUEST";
export const SIGN_EMAIL_SUCCESS = "SIGN_EMAIL_SUCCESS";
export const SIGN_EMAIL_FAILURE = "SIGN_EMAIL_FAILURE";
